### ISSUE TITLE
Login with SEEDS Light Wallet [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1039]
**Summary**
As a DAO user I would like to be able to login (and sign transactions) with the SEEDS Light Wallet

**AC**

- [x] Add "Login with SEEDS Light Wallet" Button above Anchor to Login Screen  (colour of button #3C954E)
- [ ] Update Copy above login screen (@sceenius )
- [x] Connect LW to DHO

@n13 can you help with the specs and more info? 

## Specs

There is a package on npm

https://www.npmjs.com/package/ual-seeds-wallet

This should be integrated alongside the existing ual-anchor

And it should just work after that since it's implementing the UAL spec. 

The wallet will be able to sign starting with version 2.8.3

2.8.3 is about to be released or is already released

2.9.0 and up will also work of course

There is also a version on Testflight which is already out there, in case 2.8.3 is not up yet

**Comment by jmgayosso** [comment]
Hi @n13! I implemented the LW so now you can test on dev, but we have an issue, currently LW is not notifying to UAL when a transaction is signed or rejected so the app all time still on LW modal , you can find the implementation code linked to this ticket.

https://github.com/hypha-dao/dho-web-client/pull/1077

**Comment by n13** [comment]
It should work from version 2.8.3

**Comment by jmgayosso** [comment]
> #1077
I am using the latest LW version

![Screenshot_2022-05-03-10-29-25-286_com android vending](https://user-images.githubusercontent.com/58195358/166485031-80c9a658-ffe2-405d-aef5-fc52860cf74d.jpg)

**Comment by jmgayosso** [comment]
@leonieherma1 this is implemented now on dev, but lw does not support tesnet, do you want me to implement this on mainet (prod)???

**Comment by leonieherma1** [comment]
@jmgayosso yes if we don't have another choice, let's add it on prod (can we put the light wallet on top on the login screen?)

<img width="492" alt="image" src="https://user-images.githubusercontent.com/75991832/167698316-5ea8c3be-51bc-4ab3-8149-9c28c4b31acd.png">

**Comment by sceenius** [comment]
Yes, for prod, this is alpha stage and we need to test this asap.

Thanks
Joachim

**Comment by jmgayosso** [comment]
Hi @leonieherma1 @n13 , I implemented this on prod does not work for me. the same issue that in dev. now you can test it on prod env.

**Comment by jmgayosso** [comment]
@leonieherma1 @n13 , I changed the telos enpoint for prod from https://api.telos.kitchen to https://api.telosfoundation.io, so you can test on prod, now I can login but profile page does now working with LW but if you login with Anchor works. can you test if works for you please?

**Comment by leonieherma1** [comment]
@jmgayosso @n13 I still get stuck at the login:

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/75991832/170779927-dac7e829-4bfa-4d27-b782-4e789c60b143.png">


Joachim can't see his profile in the sidebar when he logs in with LW:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/75991832/170779970-1ad46d0f-656f-4805-9da6-3d7e5620d565.png">
