### ISSUE TITLE
[R] Enrollment not working

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#313]
Expected: Enroller is able to enroll new members
Actual: receiving transaction error:

enroll
assertion failure with message: setting hvoice_token_contract does not exist

Copied:
```User: joachimstroh
Action: 0
Contract: dao.hypha
Method: enroll
Data: {"enroller":"joachimstroh","applicant":"freeminister","content":"Samara DHO member"}
```

The enrollment is working when adding manually in the Block Explorer -  https://telos.bloks.io/account/dao.hypha?loadContract=true&tab=Actions&account=dao.hypha&scope=dao.hypha&limit=100&action=enroll

**Comment by dappdever** [comment]
Can you try this again? I deployed an update to ignore the new hvoice_token_contract.

**Comment by sceenius** [comment]
Still no luck - enroll assertion failure with message: setting hvoice_token_contract does not exist
Tried user "freeminister"and marcelorossi (latest two)

**Comment by dappdever** [comment]
ah, found that code one other spot that I needed to comment out.  I redeployed and enrolled these two.

**Comment by sceenius** [comment]
tested previously on prod, moving to done
